spring.application.name=product-service
	
server.port= 8051
	
spring.datasource.url=jdbc:mysql://localhost:3306/productms?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Finastra123$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
